### ISSUE TITLE
Users able to export pdf and echo assembly instructions

### ISSUE THREAD

**Issue by hainesm6** [LondonBiofoundry/basicsynbio_frontend#10]

**Comment by Benedict-Carling** [comment]
Hi @hainesm6 would it be possible to update basicsynbio to 0.2.0 with the pdf and echo functionality included, this would help me complete this task, thanks

**Comment by hainesm6** [comment]
Here's [v0.3.0](https://pypi.org/project/basicsynbio/) @Benedict-Carling 🎆 🍾

**Comment by Benedict-Carling** [comment]
Thanks @hainesm6 I have the export echo instructions working, however I have ran into another issue on exporting pdfs in the backend, its because the latest PyPI version 0.3.0 doesn't contain `csv_xlsx_files/clip_master_mix.csv` which is needed when 
```python
COMPONENTS = pd.read_csv("csv_xlsx_files/clip_master_mix.csv")
```
we could add csv files to out manifest.ini by adding
```bash
include ./csv_xlsx_files/*.csv
```
I think everything included might need to be inside the basicsynbio folder in which case
```bash
include ./basicsynbio/csv_xlsx_files/*.csv
```
another option would be to include the contents of the csv as a pandas array directly In the code
```python
COMPONENTS = pd.array([
        'Component','Volume per clip (µL)',
        'Promega T4 DNA Ligase 10x Buffer','3',
        'Water','15.5',
        'NEB BsaI-HFv2','1',
        'Promega T4 DNA Ligase','0.5'
], dtype=str)
```
Im happy to work on this and make a pull request into basicsynbio with the solution but let me know which one you think is best, I think the final idea is the simplest.

**Comment by hainesm6** [comment]
Hi @Benedict-Carling! I think the second solution where we just hard code the `COMPONENTS` constant makes the most sense. It's not much data and it won't change so no need for a seperate csv file. I'll keep an eye out for the pull-request 😁

**Comment by hainesm6** [comment]
Ok we've now got [v0.4.0](https://pypi.org/project/basicsynbio/0.4.0/) 🎆

**Comment by Benedict-Carling** [comment]
Completed
